### ISSUE TITLE
Passing additional options via entry.toml

### ISSUE THREAD

**Issue by ioncodes** [llvmenv/llvmenv#121]
I'm trying to pass `LLVM_ENABLE_EH` and `LLVM_ENABLE_RTTI` to the build step. While looking through the source code I figured out that we are able to pass these through `entry.toml`. I edited the file:

```toml
[llvm-mirror]
url = "https://github.com/llvm-mirror/llvm"
target = ["X86"]
option = { LLVM_ENABLE_EH = "ON", LLVM_ENABLE_RTTI = "ON" }
```

This does not seem to work. Am I doing something wrong?
